#+TITLE: PSOrgMode - A module for implementing Emacs` org-mode in PowerShell
#+AUTHOR: Timothy Aldrich
#+EMAIL: timothy.r.aldrich@gmail.com
#+FILETAGS: org powershell

| Status: | Pre-release |
| Location: | [[https://github.com/aldrichtr/PSOrgMode][github]]
| Version: | 0.0.1 |

* Welcome to the PSOrgMode project

PSOrgMode is a PowerShell module for working with [[https://orgmode.org][org-mode]]
files.

* Installation
  Currently, this module is in pre-release status, so it is not published to the
  PSGallery.  If you'd like to install the module before the first release:
  #+BEGIN_SRC powershell
  git clone https://github.com/aldrichtr/PSOrgMode.git
  cd PSOrgMode
  Import-Module .\PSOrgMode\PSOrgMode.psd1
  #+END_SRC

* Usage
  Convert org-mode text to an object, similar to JSON, CSV etc.
  #+BEGIN_SRC powershell
  $o = Get-Content .\path\to\file.org | ConvertFrom-OrgMode
  $o | Get-OrgHeadline | ft
  #+END_SRC

  #+BEGIN_EXAMPLE
  Level State Priority Title                                 Tracking Timestamp    Scheduled Deadline Closed Commented
  ----- ----- -------- -----                                 -------- ---------    --------- -------- ------ ---------
      1 TODO  [#A]     First level one headline
  #+END_EXAMPLE

* Why ?
  I /love/ emacs.  I've used it , and org-mode as my daily work environment for
  ... I don't know how long, but it's decades.

  New job, new tools, and I found myself without emacs on my workstation.

  I didn't want to like PowerShell, but after using it for a while now, I have to
  say, I really do.

  So, I have years of notes, old projects, and reference material in a folder of
  org files, and I want a way to use them, so... PSOrgMode.

* Project Roadmap
  I'm just getting started on the project, and I will move this part into the
  issue/project section, but as a high-level outline of what I want to do with
  this project:
  - Parse org-mode text into an object hierarchy (Parser)
  - Write objects to org-mode format (Interpreter)
  - Work with TODO items, timestamps and planning (Agenda)

  Some other Orgmode functionality that is interesting and I may add in future
  versions:
  - Work with source code blocks and babel calls (Tangle)
  - Convert org-mode text to other formats (Export)
